# Generated by Django 4.0.4 on 2022-05-24 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdkapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_number',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='row_nubmer',
            new_name='row_id',
        ),
    ]
