# Generated by Django 4.0.4 on 2022-05-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdkapp', '0002_rename_order_number_order_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount',
            new_name='amount_usd',
        ),
        migrations.AddField(
            model_name='order',
            name='amount_rub',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
