# Generated by Django 4.0.4 on 2022-05-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdkapp', '0003_rename_amount_order_amount_usd_order_amount_rub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('rate', models.IntegerField()),
            ],
        ),
    ]
