# Generated by Django 4.0.4 on 2022-05-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdkapp', '0005_order_message_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TGUser',
            fields=[
                ('tg_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
