# Generated by Django 4.0.4 on 2022-05-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdkapp', '0006_tguser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount_rub',
            field=models.IntegerField(verbose_name='Сумма в рублях * 10 000'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount_usd',
            field=models.IntegerField(verbose_name='Сумма в долларах * 10 000'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='message_sent',
            field=models.BooleanField(default=False, verbose_name='Уведомление о готовности заказа отправлено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='row_id',
            field=models.IntegerField(verbose_name='Номер строки в google sheets'),
        ),
    ]
