version: "3.9"

services:
  postgres:
    container_name: pg_db
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: "vdkdb"
      POSTGRES_USER: "vdkuser"
      POSTGRES_PASSWORD: "vdkpass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - vdknetwork

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "gvgeorge@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "vdkpass"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    restart: unless-stopped

    networks:
      - vdknetwork

  redis:
      container_name: redis

      image: "redis:alpine"

      ports:
        - "6379:6379"

      volumes:
        - $PWD/redis-data:/var/lib/redis
        - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

      environment:
        - REDIS_REPLICATION_MODE=master

      networks:
        - vdknetwork

  vodokanal:
    build: .
    container_name: vodokanal
    environment:
      DJANGO_SECRET_KEY: "django-insecure-@cr8c#d-_$$%bvt#&fy1vtmo9ln8yu#50(q7ck#vg$$i0$$a7ashh"
      TG_API_KEY: "5363088590:AAHQpK6G30VyGQvo0kEWJk2ZyLE2JnWkKkw"
    depends_on:
      - postgres
      - redis
    command: 
      sh -c "python3 manage.py migrate"
      sh -c "python3 manage.py run_bot"

    ports:
        - 8000:8000
    networks:
      - vdknetwork

  celery:
    build: .
    command: celery -A vdkproject worker -l info
    environment:
      DJANGO_SECRET_KEY: "django-insecure-@cr8c#d-_$$%bvt#&fy1vtmo9ln8yu#50(q7ck#vg$$i0$$a7ashh"
      TG_API_KEY: "5363088590:AAHQpK6G30VyGQvo0kEWJk2ZyLE2JnWkKkw"

    volumes:
      - .:/code
    depends_on:
      - postgres
      - redis
    networks:
      - vdknetwork

  celery-beat:
    build: .
    command: celery -A vdkproject beat -l info
    environment:
      DJANGO_SECRET_KEY: "django-insecure-@cr8c#d-_$$%bvt#&fy1vtmo9ln8yu#50(q7ck#vg$$i0$$a7ashh"
      TG_API_KEY: "5363088590:AAHQpK6G30VyGQvo0kEWJk2ZyLE2JnWkKkw"
    volumes:
      - .:/code
    depends_on:
      - postgres
      - redis
    networks:
      - vdknetwork


networks:
  vdknetwork:
    driver: bridge